name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: mukharomdev
  GITHUB_REPOSITORY: mukharomdev/Rust-docs-indonesia
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

on: 
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: |
          set -x
          apt-get update
          apt-get install -y git make python3 python3-pip python3-sphinx 
          pip3 install --no-cache-dir sphinx-rtd-theme
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: "cp -rf docsourc/* docs/ && docs/buildsite.sh"
        shell: bash
